### ISSUE TITLE
Maya/UserSetup.py can't import avalon

### ISSUE THREAD

**Issue by gabormarinov** [getavalon/setup#1]
in Maya pythonpath contains the avalon_setup folder where is an avalon.py file. UserSetup.py imports that file instead of avalon-setup\git\avalon-core\avalon module, so the avalon menu installation fails.

**Comment by mottosso** [comment]
You're right, it's an inherent problem calling the CLI the same as the top-level package.. For now I think the safest thing to do is *not* to have the `avalon-setup` directory on your PYTHONPATH or current working directory when starting Maya.
