### ISSUE TITLE
included gridfs, bson modules cause python.exe runtime error

### ISSUE THREAD

**Issue by gabormarinov** [getavalon/setup#2]
![image](https://user-images.githubusercontent.com/8620515/27881217-1f0b816e-61c8-11e7-842a-b810c701ad8b.png)

Importing gridfs, bson modules from avalon-setup\bin\pythonpath\ folder cause python.exe runtime error in  a conda environment.
Python info:
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:21:39) [MSC v.1900 64 bit (AMD64)] on win32

Replacing them with fresh installs from pypi eliminates the problem.

**Comment by mottosso** [comment]
Thanks for this @gabormarinov, anyone searching for this problem will now be able to benefit from this solution; i.e. to install from PyPI.
