### ISSUE TITLE
Windows Path with spaces fails

### ISSUE THREAD

**Issue by rjmoggach** [getavalon/setup#8]
Setting Windows `Path` to include something like:

```
D:\Dropbox (Company Name)\tools\Avalon
```

fails with Python path error.

Current workaround is to create a junction to a folder without a space.

```
mklink /j D:\Dropbox (Company Name) D:\DropboxCompany
```

and then set the Path accordingly. 

Not sure if there can be some error checking added?

**Comment by BigRoy** [comment]
Would you happen to have the error traceback? That could make it easier to find where it's failing.

**Comment by rjmoggach** [comment]
I don't actually - I could probably reproduce. I think it's a Python error and not Avalon specific.
